### ISSUE TITLE
lib/macosx/libblosc.dylib missing in Fiji download for Mac

### ISSUE THREAD

**Issue by axtimwalde** [fiji/fiji#263] opened 2020-08-10 17:14 UTC
Under unknown circumstances the file will also never be installed by the updater although it is present on the Java-8 update site.
Proposed solution: include in the official Fiji download for Mac.

**Comment by ctrueden** [comment] 2020-09-05 05:13
I started on a short-to-medium-term fix for this awhile back, but didn't end up finishing it. @hinerm I'm tagging you in, in case you have the bandwidth to finish it before I get back.

My idea is a new script in https://github.com/fiji/fiji-builds called `is-fiji-complete.sh` with rough contents as follows:

```shell
#!/bin/sh

# Check the ImageJ installation for any missing (i.e., NOT_INSTALLED) files
# from activated update sites, excluding files from non-matching platforms.
# Echoes the list of missing files to stdout, and returns an exit code
# equaling the number of missing files (max 255).

FIJI_HOME=$1
test "$FIJI_HOME" || { echo "[ERROR] Please specify folder for Fiji.app." && exit 1; }

case "$(uname -s),$(uname -m)" in
  Linux,x86_64) launcher=ImageJ-linux64 ;;
  Linux,*) launcher=ImageJ-linux32 ;;
  Darwin,*) launcher=Contents/MacOS/ImageJ-macosx ;;
  MING*,*) launcher=ImageJ-win32.exe ;;
  MSYS_NT*,*) launcher=ImageJ-win32.exe ;;
  *) echo "[ERROR] Unknown platform" && exit 2 ;;
esac

notInstalledFiles=$("$FIJI_HOME/$launcher" --update list | grep NOT_INSTALLED)
test "$notInstalledFiles" || exit 0
echo "$notInstalledFiles"
count=$(echo "$notInstalledFiles" | wc -l)
test "$count" -gt 255 && exit 255 || exit $count
```

And then, when updating the Fiji installation (either in `.travis/build.sh` at the `./update-fiji.sh "$FIJI_HOME" || exit 2` part, or in `update-fiji.sh` itself), instead of just updating once, update _in a loop_ until `is-fiji-complete.sh` returns true. Maybe with some fail fast mechanism detecting if a particular update _changes nothing_. (But you cannot just check for "fewer updateable/uninstalled files" because in my experience, repeated updates sometimes install one file while removing two, but then the next update installs the two again. So weird!)

This should fix the libblosc on macOS issue, because the problem I observed was that a single update wasn't enough to get the macOS libblosc native library installed... but multiple updates were. In my tests, I observed some cases where at least 3 updates were needed... but sometimes less depending on the scenario. Therefore, I think it would be safest to just loop till we're sure everything has been installed. A crappy hack, I know, but probably easier than digging into the Updater to understand why this happens.

**Comment by tischi** [comment] 2020-09-10 09:45
@hinerm @ctrueden 
Thank you very much for working on this!

Could you let me know what the status is? I am sorry for pushing a bit but I am involved in two publications that depend on this which should be submitted/published in very few weeks. 

In fact I need it to work even earlier than this for some collaborative work. Would it be an option that I temporarily ship the `libblosc.dylib` file with my Update Site? It would probably not end up in the `/lib/macosx` folder, but would it still work?

**Comment by tischi** [comment] 2020-09-11 14:22
@ctrueden @hinerm 

FYI: When I updated a Fiji that I downloaded yesterday it asked me:
![image](https://user-images.githubusercontent.com/2157566/92936827-e0882f00-f44a-11ea-9e32-849d7722f12d.png)
Does that mean you fixed it?

**Comment by tischi** [comment] 2020-09-11 16:06
...or maybe this is an behaviour that we have seen before: if one downloads a fresh Fiji and then updates it **without at the same time adding any update site**, it downloads the libblosc,dylib. At least I seem to remember something like this.

**Comment by axtimwalde** [comment] 2020-09-11 17:12
Can you try this?  "Download a fresh Fiji and then updates it without at the same time adding any update site"? One maybe less to worry about ;).

**Comment by tischi** [comment] 2020-09-12 09:24
> Download a fresh Fiji and then update it without at the same time adding any update site

That is what I have done. This seemed to work for me. But still it would be nicer if one would not have to do this.

**Comment by axtimwalde** [comment] 2020-09-14 13:24
I agree. But I wanted to make sure this isn't a "may be", so the issue still stands @hinerm ?

**Comment by hinerm** [comment] 2020-09-25 17:57
@axtimwalde @tischi I don't have access to a Mac to do in-depth manual testing, but as far as I can tell (from looking at the `nojre` and `macosx` downloads, which are built from enabling the `Java-8` and `Fiji` update sites on a fresh ImageJ) `lib/macosx/libblosc.dylib` seems to be properly tracked and provided by the `Java-8` update site..

**Comment by ctrueden** [comment] 2020-09-25 18:08
@hinerm The issue is that when downloading a fresh Fiji for macOS, the `libblosc.dylib` is not there, even though according to the `db.xml.gz` it should be. It's a bug in the Updater.

Could you please check whether the downloadable bundle still suffers from that defect? If so, the workaround I was planning to implement—`is-fiji-complete.sh` in `fiji/fiji-builds` repository—is described above.

**Comment by hinerm** [comment] 2020-09-29 14:40
@ctrueden the mac and nojre bundles on https://imagej.net/Fiji/Downloads contain `libblosc.dylib`. Are there other bundles to check?

**Comment by ctrueden** [comment] 2020-10-01 12:28
Hmm, weird. I wonder why they are there now?

**Closed by ctrueden** 2020-10-01 12:28 UTC
Labels: deployment, java8, updater

**Comment by hinerm** [comment] 2020-10-01 16:19
@ctrueden It looks like it was missing from the `2020-09-02` build, and then appeared in `2020-09-21`... I can't figure out why?

**Comment by tischi** [comment] 2020-10-02 07:27
Just to confirm, I downloaded a Fiji on MacOS yesterday and the `libblosc.dylib` was there. It wasn't a few weeks ago.
