### ISSUE TITLE
Update to mpicbg 1.0.0 release

### ISSUE THREAD

**Issue by ctrueden** [fiji/fiji#113] opened 2015-03-09 19:03 UTC
@axtimwalde released `mpicbg:mpicbg:1.0.0`, but the Fiji stack has not been upgraded to use it. From my prior discussion with @axtimwalde a while back, it sounded a bit involved, due to backwards incompatibilities.

@axtimwalde This change is not urgent on my end, but IIRC, you need the new functionality for something eventually? So just to maintain clear communication and track the progress, I am assigning this issue to you. Please let me know if there is anything I can do to assist!

**Comment by axtimwalde** [comment] 2015-03-11 03:14
Trying to find time to migrate some of the other dependencies soon.  Recently motivated and helped @StephanPreibisch to migrate SPIM_Registration which is not yet finished as far as I can see
https://github.com/bigdataviewer/SPIM_Registration/commits/mpicbg_double
How is Stitching?

**Comment by StephanPreibisch** [comment] 2015-03-19 14:07
Thanks for dealing with this guys while I was on holidays :) The SPIM_Registration is done converting it to the new mpicbg_double ... just merged the branch to the current master ...

**Comment by axtimwalde** [comment] 2015-03-19 14:21
Hi Steffi,

thanks a lot!

It will not work though because there is a critical bug in ransac-test
in 1.0.0 (compile yes, work not).

Can you please update to mpicbg-1.0.1 ?  No further changes.

Thanks,
Stephan

**Comment by StephanPreibisch** [comment] 2015-03-19 14:51
Done ... https://github.com/bigdataviewer/SPIM_Registration/commit/e1734560a87d7ef34729689a43dd51fc9e69f418

**Comment by StephanPreibisch** [comment] 2015-03-19 15:03
Stitching is converted as well: https://github.com/fiji/Stitching/commit/6b154190a2a43c7952a7d3474f01700bcc7addeb

Not tested though

**Comment by StephanPreibisch** [comment] 2015-03-19 15:06
Descriptor-based registration is converted as well: https://github.com/bigdataviewer/Descriptor_based_registration/commit/33b33d2e8db40bdad27f2cdd48230994cc2668a7

Also not tested.

**Comment by StephanPreibisch** [comment] 2015-03-19 15:11
When do you plan to update? @axtimwalde

**Comment by axtimwalde** [comment] 2015-03-19 18:26
Whenever the other dependents are fixed.  I am working on this.

On another note, I do not even dare to think about what all can go wrong
during this update.  We have absolutely no reliable mechanism other than
manual traversal to assure compatibility of individual components in the
Fiji distribution.

Surely making it worse than it is, the project is still pretty small ;).

**Comment by ctrueden** [comment] 2015-03-19 18:38
> We have absolutely no reliable mechanism other than manual traversal to assure compatibility of individual components in the Fiji distribution.

A new enforcer rule in the `scijava-maven-plugin` is the perfect place to add such a feature. We currently ensure that builds are reproducible this way—now we just need a "SemVer dependency convergence" rule that ensures that when two conflicting dependency versions exist in the dependency tree, they are always at the same major version. This would be a huge step toward avoiding JAR skew, because we could then run this rule against the [fiji/fiji](https://github.com/fiji/fiji) repository before uploading stuff.

**Comment by ctrueden** [comment] 2015-03-19 18:40
BTW, the issue tracking the aforementioned feature is https://github.com/scijava/scijava-maven-plugin/issues/7

**Comment by axtimwalde** [comment] 2015-03-19 22:48
Thanks a lot @ctrueden!

I have commented on this issue with a simple proposal for consistency
assurance that would enable us to deal with the much more practical
situation that parents do not match and that eggs do not have to create
hens before being laid ;).

My understanding of the

https://github.com/ning/maven-dependency-versions-check-plugin

is that it only covers dependencies but not modules.  It may, however,
do just exactly what I proposed.

**Comment by axtimwalde** [comment] 2015-03-20 01:55
@ctrueden @hinerm @StephanPreibisch I have updated the known remaining dependents of TrakEM2 and mpicbg and the dependencies themselves:

FS_Align_TrakEM2-2.0.1, Reconstruct_Reader-2.0.2, TrakEM2_Archipelago-2.0.1, blockmatching_-2.1.1, register_virtual_stack_slices-2.0.3, mpicbg-1.0.1, mpicbg_1.0.1, legacy-imglib1-1.1.2-DEPRECATED, pom-trakem2-1.3.2, mpicbg-trakem2-1.2.2, TrakEM2_-1.0f, jitk-tps-1.1.1, trakem2_tps-1.1.1

.  Together with releases of

SPIM_Registration, Stitching, Descriptor_based_registration

we would be ready to go for the long pending update.  Some care and thought pending before eventually doing it...

**Comment by ctrueden** [comment] 2015-03-20 03:12
Cool, thanks for the hard work, guys! When all is ready, you can signal so by filing a PR against the [pom-fiji](https://github.com/fiji/pom-fiji) project with all the updated release version numbers!

**Comment by axtimwalde** [comment] 2015-03-27 01:12
@ctrueden I filed a PR.  We will have to synchronize this release with
bigdataviewer and potential dependents because the artifacts

SPIM_Registration-2.1.5, Stitching_-3.0.1,
Descriptor_based_registration-2.0.8

depend on

mpicbg-1.0.1,
legacy-imglib1-1.1.3-DEPRECATED

and

bigdataviewer-core-1.0.8,  spimdata-1.0.0-beta-5,
pom-bigdataviewer-1.1.2

and probably others that depend on it (MaMuT?).  I have reached my
limits here and have triggered some help requests.  If you have any
tools in the pipe that would help resolving this conclusively, I'd be
glad to learn about them.

Thanks,
Stephan

**Comment by ctrueden** [comment] 2015-03-27 03:51
Thanks for all your efforts, @axtimwalde. FYI, I am on vacation from now through the end of next week, but I'll be back on the case on Monday, April 6. Hopefully that gives various parties enough time to resolve any remaining issues before we update the components in Fiji.

**Comment by axtimwalde** [comment] 2015-03-27 14:52
Thanks @ctrueden and enjoy your vacation!  @tpietzsch and @tinevez could you please have a look at [BigDataViewer](https://github.com/bigdataviewer) and [MaMuT](http://sites.imagej.net/MaMuT/) and potential dependencies?  We can only update everything at once or either part is broken.  Thanks a lot in advance!

**Comment by tinevez** [comment] 2015-03-29 18:32
@axtimwalde : just tested BigDataViewer and MaMuT, with a just-fully-updated Fiji.
Both works.

**Comment by axtimwalde** [comment] 2015-03-30 17:37
@tinievez, Fiji is not updated.  Before we update, we have to consider the following: BigDataViewer and MaMuT are independent of mpicbg, but SPIM_Registration depends on both and comes through the BigDataViewer update site.  SPIM_Registration also requires and update of BigDataViewer (bigdataviewer-core-1.0.8, spimdata-1.0.0-beta-5, pom-bigdataviewer-1.1.2), i.e. the Fiji update site and the BigDataViewer update site have to be updated in synchrony with Fiji slightly ahead to prevent anybody consuming BigDataViewer upgrade without Fiji upgrade.

What I do not know is how MaMuT does with the latest BigDataViewer, have you tested that?

**Comment by tinevez** [comment] 2015-03-30 20:09
@axtimwalde Ok let me test it tomorrow. 
Building from source, with full update to dependencies should yield the answer right? 
I am checking against

mpicbg-1.0.1,
legacy-imglib1-1.1.3-DEPRECATED
bigdataviewer-core-1.0.8,  spimdata-1.0.0-beta-5,
pom-bigdataviewer-1.1.2

**Comment by StephanPreibisch** [comment] 2015-03-31 10:09
The reason SPIM_Regisstration needs an update is simply that Tobias changed the constructor of BDV to work with AbstractSpimData instead of MinimalSpimData I think. A very important change though :)

**Comment by tinevez** [comment] 2015-03-31 12:56
@axtimwalde so I checked out the 'mpicbg' branch of the pom-fiji repo. I then used the v9.0.0-SNAPSHOT it provided as a parent pom for MaMuT, compiled, and checked that it pulled the desired version of dependencies:
- mpicbg-1.0.1,
- bigdataviewer-core-1.0.8, 
- spimdata-1.0.0-beta-5,
Apart from the enforcer complaint, it compiles without any problem.
It also works as expected when ran with a real sample.

**Comment by axtimwalde** [comment] 2015-03-31 16:47
@tinevez thanks!  I take this as a: Yes, everything works. :)  Now we would have to synch with @tpietzsch to get the Fiji and BDV updates up approximately parallel.  Next week Monday would be a good time for me.

**Comment by tpietzsch** [comment] 2015-03-31 17:49
@axtimwalde Monday is fine. Note that the BDV is now distributed via the main Fiji update site. BDV update site is empty, currently. So in principle @StephanPreibisch or you could also upload the latest BDV version in one big upload to the main update site (probably a good idea). Would next week Tuesday also work for you?

**Comment by tinevez** [comment] 2015-03-31 19:51
@tpietzsch Regarding the empty BDV update site: in that case we could remove it from the http://fiji.sc/List_of_update_sites
Ok go?

**Comment by StephanPreibisch** [comment] 2015-04-01 14:53
Next Monday I am flying back to New York, so I have time but no internet throughout the day. Also, it is a public holiday in Germany I heard.

**Comment by axtimwalde** [comment] 2015-04-01 15:42
Tuesday is fine for me.

**Comment by ctrueden** [comment] 2015-04-06 15:55
@tinevez @tpietzsch It is probably OK to remove the old BDV site from the list of update sites, although I was a bit reluctant since we have not thoroughly tested what that does to people's installations. Remember that the Updater scrapes that wiki page for known sites, and if previously available sites go missing, strange stuff might happen. If you do remove it, _please_ test what happens to a Fiji installation—both with the BDV update site enabled, as well as disabled. If there is catastrophic failure, we would have to very quickly add the site back to the list (marking it obsolete in the comments), and file an issue with the Updater to improve behavior in the future.

> Tuesday is fine for me.

Best of luck to all with the update. I will be in the office 8am - 5pm CDT, in case there are catastrophic problems with which you need assistance.

**Comment by tinevez** [comment] 2015-04-14 07:15
@ctrueden @tpietzsch 
I just made several tests with the Wiki. 

* If I remove the BDV update site line from http://fiji.sc/List_of_update_sites, and launch a Fiji installation without the BDV site checked, nothing special happens. The BDV site just disappears from the updater.

* If I do the same on an installation with the BDV site checked, nothing happens as well. The site again is not shown on the updater, regardless whether it was checked or not prior to removal on the wiki page. 

I guess it works well because subscribing to the site in the updater has no impact on the installation: the versions shipped from the fiji site shadow the obsolete ones

**Comment by ctrueden** [comment] 2015-04-14 13:38
@tinevez: Great, glad to hear it! So you think that, in general, removing update sites from the list will work out OK then?

The reason for my hesitation stems from my experience with the update sites "Bio-Formats" (which was labeled "Bio-Formats 4") and "Bio-Formats-5" (which was labeled "Bio-Formats 5"). After Fiji stopped shipping Bio-Formats 4.x, I changed the "Bio-Formats" site to ship Bio-Formats 5.x, and deleted the previous "Bio-Formats-5" site. Then I symlinked it to Bio-Formats, so the two were the same. This seemed to work OK for people who had either (or neither) checked.

However, I also [consolidated the entries on the "List of update sites" page](http://imagej.net/index.php?title=List_of_update_sites&diff=9830&oldid=9823), and that seemed to cause more weirdness. We still occasionally receive reports ([[1]](http://imagej.1557.x6.nabble.com/Fiji-updater-tp5009061p5009065.html), and I swear there was one a couple weeks ago too, but I can't find it now) mentioning "Bio-Formats 4" and/or "Bio-Formats 5" in their Updater UI. So it seems safest to minimize removal of update sites from that list.

Anyway, I guess the proper fix is in the Updater code: just be smarter about handling changes to that list. We should probably flag locally which update sites came from that list, versus which were added by hand. That would make it much easier to stay in sync.

**Comment by tinevez** [comment] 2015-04-14 13:55
@ctrueden Yes, but let me stress out that I did not test the case where the removed update site contained jars that were not shadowed by other update sites. 
That might the context behind the reports you mention.

The problem is that this depends on the end user: if we remove an update site and someone has a non-up to date Fiji, that might cause havoc.

**Comment by ctrueden** [comment] 2015-04-15 20:49
This issue is completely resolved now, right? We can close it?

**Closed** 2015-04-16 05:28 UTC
