### ISSUE TITLE
Some .ND2 files won't open

### ISSUE THREAD

**Issue by wyneh9080** [fiji/fiji#174] opened 2017-09-21 18:48 UTC
I've been having trouble opening about every 9/10 files I have saved.  I can open them in NIS viewer but not in fiji.  I get a few different error options one saying that it cannot open files with the .nd2 extension and one saying that there was a java error.  As I said certain files will still open on Fiji and all of them open on NIS.  Is it a problem with Fiji or the file type? What can I do to fix it?

**Comment by ctrueden** [comment] 2017-09-23 07:06
The ND2 format is handled by [Bio-Formats](https://imagej.net/Bio-Formats). Please see the [Bio-Formats bug reporting](https://docs.openmicroscopy.org/bio-formats/5.7.1/about/bug-reporting.html) page for details on how to report an issue to that project. The [bug reporting best practices](https://imagej.net/Bug_reporting_best_practices) page might also be useful.

For these kinds of file-format-related issues, it is usually necessary to receive A) a non-working example file; and B) a specific description of the faulty behavior (usually an error message)—otherwise, the developers cannot reproduce the issue in order to troubleshoot it.

I'm going to close this issue here, since the next step is a bug report to the Bio-Formats project. But feel free to reopen this issue if you have reason to believe the issue is somewhere else in Fiji.

**Closed by ctrueden** 2017-09-23 07:06 UTC
